/*
 * config.h (for libspeex)
 *
 * This is a manual configuration for building with Emscripten/WASM.
 * It replaces the file that would normally be generated by a ./configure script.
 */

#ifndef CONFIG_H
#define CONFIG_H

/* We are building a fixed-point version */
#define FIXED_POINT 1

/* Speex uses the KISS FFT library which is included in its source */
#define USE_KISS_FFT 1

/* For WASM static builds, EXPORT should be defined as nothing */
#define EXPORT

/* Optional: Define package info */
#define PACKAGE_NAME "Speex"
#define PACKAGE_VERSION "1.2.1" /* Or whatever version you downloaded */
#define PACKAGE_STRING PACKAGE_NAME " " PACKAGE_VERSION
#define PACKAGE_BUGREPORT "https://github.com/xiph/speex/issues"

#endif /* CONFIG_H */
